/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackgroundRemoverRouteImport } from './routes/background-remover'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductPhotoBackgroundRemoverRouteImport } from './routes/product-photo-background-remover'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TransparentPngRouteImport } from './routes/transparent-png'
import { Route as DocsSplatRouteImport } from './routes/docs.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundRemoverRoute = BackgroundRemoverRouteImport.update({
  id: '/background-remover',
  path: '/background-remover',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductPhotoBackgroundRemoverRoute =
  ProductPhotoBackgroundRemoverRouteImport.update({
    id: '/product-photo-background-remover',
    path: '/product-photo-background-remover',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparentPngRoute = TransparentPngRouteImport.update({
  id: '/transparent-png',
  path: '/transparent-png',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/background-remover': typeof BackgroundRemoverRoute
  '/privacy': typeof PrivacyRoute
  '/product-photo-background-remover': typeof ProductPhotoBackgroundRemoverRoute
  '/terms': typeof TermsRoute
  '/transparent-png': typeof TransparentPngRoute
  '/docs/$': typeof DocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/background-remover': typeof BackgroundRemoverRoute
  '/privacy': typeof PrivacyRoute
  '/product-photo-background-remover': typeof ProductPhotoBackgroundRemoverRoute
  '/terms': typeof TermsRoute
  '/transparent-png': typeof TransparentPngRoute
  '/docs/$': typeof DocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/background-remover': typeof BackgroundRemoverRoute
  '/privacy': typeof PrivacyRoute
  '/product-photo-background-remover': typeof ProductPhotoBackgroundRemoverRoute
  '/terms': typeof TermsRoute
  '/transparent-png': typeof TransparentPngRoute
  '/docs/$': typeof DocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/background-remover'
    | '/privacy'
    | '/product-photo-background-remover'
    | '/terms'
    | '/transparent-png'
    | '/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/background-remover'
    | '/privacy'
    | '/product-photo-background-remover'
    | '/terms'
    | '/transparent-png'
    | '/docs/$'
  id:
    | '__root__'
    | '/'
    | '/background-remover'
    | '/privacy'
    | '/product-photo-background-remover'
    | '/terms'
    | '/transparent-png'
    | '/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackgroundRemoverRoute: typeof BackgroundRemoverRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductPhotoBackgroundRemoverRoute: typeof ProductPhotoBackgroundRemoverRoute
  TermsRoute: typeof TermsRoute
  TransparentPngRoute: typeof TransparentPngRoute
  DocsSplatRoute: typeof DocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-remover': {
      id: '/background-remover'
      path: '/background-remover'
      fullPath: '/background-remover'
      preLoaderRoute: typeof BackgroundRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-photo-background-remover': {
      id: '/product-photo-background-remover'
      path: '/product-photo-background-remover'
      fullPath: '/product-photo-background-remover'
      preLoaderRoute: typeof ProductPhotoBackgroundRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparent-png': {
      id: '/transparent-png'
      path: '/transparent-png'
      fullPath: '/transparent-png'
      preLoaderRoute: typeof TransparentPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackgroundRemoverRoute: BackgroundRemoverRoute,
  PrivacyRoute: PrivacyRoute,
  ProductPhotoBackgroundRemoverRoute: ProductPhotoBackgroundRemoverRoute,
  TermsRoute: TermsRoute,
  TransparentPngRoute: TransparentPngRoute,
  DocsSplatRoute: DocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
